# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=255)),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_a', to='inspection.PDF'),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_b', to='inspection.PDF'),
        ),
    ]
