# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('option_string', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='/opt/test_auto_ui/test_auto_ui/settings/../../media/pdf')),
            ],
        ),
        migrations.AddField(
            model_name='cvtest',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.Option'),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_a', to='inspection.PDF'),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_b', to='inspection.PDF'),
        ),
    ]
