# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('test_choices', models.CharField(choices=[('Any', 'Any'), ('All', 'All')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='cvtest',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.Option'),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_a', to='inspection.PDF'),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='pdf_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_b', to='inspection.PDF'),
        ),
    ]
