# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_string',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
