# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20160609_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvtest',
            old_name='test_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='cvtest',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cvtest',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
